<?php
    /** 
     * @var Magento\Framework\View\Element\Template $block 
     * @var DevTeam\CustomBadges\ViewModel\Product\CustomBadge $customBadgeViewModel
     * @var Magento\Framework\Escaper $escaper
    **/

    $customBadgeViewModel = $block->getData("product_custom_badge_view_model");
    $productID = $block->getData("product_id") ?? null;
    $customBadge = $customBadgeViewModel->getCustomBadge($productID);
?>

<?php if(!empty($customBadge)): ?>
    <div class="custom-badge">
        <img class="custom-badge-image" src="<?= $escaper->escapeHtml($customBadge) ?>" />
    </div>
<?php endif ?>